main: pl.gon_3t.kaigara.Kaigara
name: "Kaigara"
version: "1.7"
api-version: "1.15"

commands: #自作プラグインのコマンドを宣言
  kaigara:
    description: shulker box opener plugin.
    usage: /<command> [option]

  kg:
    description: shorten command for kaigara.
    usage: /<command> [option]
